version: '3'
services:
  mlops:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - api-network

  mlops-frontend:
    build:
      context: client/
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
