version: '3'
services:
  mlops:
    image: rohansingh9001/mlops:latest
    ports:
      - 8000:8000
    networks:
      - api-network
  mlops-frontend:
    image: rohansingh9001/mlops-frontend:latest
    ports:
      - 80:80
    networks:
      - api-network

networks:
  api-network:
    driver: bridge